env: "local"

http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s

postgres:
  host: "postgres"
  port: 5432
  user: "user"
  password: "password"
  db_name: "social_network"
  ssl_mode: "disable"

jwt:
  private_key_path: "certs/local/private.pem"
  public_key_path: "certs/local/public.pem"
